
=======
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login \
            --username "$DOCKER_USERNAME" \
            --password-stdin

      - name: Build Docker image
        run: docker build -t eyadocker123/projet-smd:latest .

      - name: Push Docker image
        run: docker push eyadocker123/projet-smd:latest